In [13]:
import torch, pickle
import networkx as nx
import numpy as np
from sklearn.metrics import f1_score
from ogb.linkproppred import PygLinkPropPredDataset
import torch_geometric.transforms as T
import statistics
import random

In [44]:
np.mean([2.07, 2.36, 1.81, 3.73, 5.01, 4.50, 3.00])

3.2114285714285713

In [49]:
data='cora'

In [55]:
data='citeseer'

In [25]:
data='pubmed'

In [56]:
adj = pickle.load(open(data + '_adj.pkl', 'rb'))
feature = pickle.load(open(data + '_feat.pkl', 'rb')).toarray()
net = nx.from_scipy_sparse_matrix(adj)
len(sorted(nx.connected_components(net), key=len, reverse=True))

438

In [57]:
nets = sorted(nx.connected_components(net), key=len, reverse=True)

In [58]:
cnt = 0
for net in nets:
    if len(net) == len(nets[0]):
        continue
    cnt += len(net)

In [59]:
len(nets[0])

2120

In [60]:
cnt

1207

In [33]:
lgst_net = nx.subgraph(net, nets[0])

AttributeError: 'set' object has no attribute 'subgraph'

In [77]:
pe = torch.load(data+'_pe_async_fluid.pt')

In [78]:
nodes = list(lgst_net)

In [79]:
random.seed(123)

In [80]:
nodes = random.sample(nodes, 100)

In [81]:
error1 = []
error2 = []
for node1 in nodes:
    for node2 in range(node1+1, len(nodes)):
        try:
            path_len = len(nx.shortest_path(lgst_net, node1, node2))
        except:
            continue
        appr_len = sum(abs(pe[node1]-pe[node2]))
        appr_len2 = min(pe[node1]+pe[node2])
        error1.append(abs(path_len-appr_len))
        error2.append(abs(path_len-appr_len2))

In [82]:
np.mean(error1), np.mean(error2)

(6.4222222222222225, 3.7333333333333334)

In [83]:
filename = f'facebook.txt'
g = nx.read_edgelist(filename,create_using=nx.Graph(), nodetype = int,  data=(("weight", float),))
adj_label = nx.adjacency_matrix(g, nodelist = sorted(g.nodes())) 
adj = (adj_label > 0).astype('int') # to binary
net = nx.from_scipy_sparse_matrix(adj)
nets = sorted(nx.connected_components(net), key=len, reverse=True)

In [84]:
pe = torch.load(data+'_pe_async_fluid.pt')
nodes = list(lgst_net)
random.seed(123)
nodes = random.sample(nodes, 100)

In [85]:
error1 = []
error2 = []
for node1 in nodes:
    for node2 in range(node1+1, len(nodes)):
        try:
            path_len = len(nx.shortest_path(lgst_net, node1, node2))
        except:
            continue
        appr_len = sum(abs(pe[node1]-pe[node2]))
        appr_len2 = min(pe[node1]+pe[node2])
        error1.append(abs(path_len-appr_len))
        error2.append(abs(path_len-appr_len2))

In [86]:
np.mean(error1), np.mean(error2)

(6.4222222222222225, 3.7333333333333334)

In [73]:
len(nets)

1

In [49]:
vertices = [v[0] for v in sorted(net.degree(), key=lambda x: x[1], reverse=True)]

In [42]:
len(net.edges(0))

6

In [4]:
np.log(2927963)

14.889817517371474

In [3]:
import statistics

In [3]:
a = [93.25, 94.75, 96.62, 99.48, 85.64, 55.47, 67.02]
np.mean(a), np.std(a)

(84.60428571428572, 15.595029297039178)

In [4]:
a = [84.74, 44.14, 37.07, 95.80, 88.68, 85.35, 98.66]
np.mean(a), np.std(a)

(76.34857142857142, 23.17591756763992)

In [5]:
statistics.harmonic_mean(a)

66.66718945656014

In [6]:
a = [89.05, 88.58, 96.58, 99.43, 0.0, 48.84, 57.98]
#np.mean(a), np.std(a)
statistics.harmonic_mean(a)

0

In [6]:
a = [92.55, 85.27, 96.36, 99.60, 85.82, 54.37, 26.25]
np.mean(a), np.std(a)

(77.1742857142857, 24.960037120589874)

In [7]:
a = [92.55, 85.27, 96.36, 99.60, 85.82, 54.37, 26.25]
#np.mean(a), np.std(a)
statistics.harmonic_mean(a)

63.01176554715486

In [50]:
a = [0, 0, 1.34, 79.36, 79.62, 77.51, 93.13]
np.mean(a), np.std(a)

(47.279999999999994, 40.834785241437054)

In [51]:
statistics.harmonic_mean(a)

0

In [ ]:
a = [0, 0, 1.34, 79.36, 79.62, 77.51, 93.13]
np.mean(a), np.std(a)

(66.192, 32.903623751799735)

In [ ]:
statistics.harmonic_mean(a)

6.288767412125091

In [5]:
a = [77.22, 68.94, 66.89, 99.41, 76.12, 53.00, 18.61]

In [10]:
a = [51.14, 50.54, 58.18, 98.80, 63.08, 38.74, 17.92]

In [13]:
a = [84.49, 80.00, 80.32, 86.49, 53.47, 41.36, 21.95]

In [25]:
a = [89.05, 88.58, 96.58, 99.43, 48.84, 57.98]

In [9]:
a = [90.25, 71.47, 95.83, 99.43, 84.79, 44.29, 39.31]

In [25]:
a = [90.24, 87.38, 96.58, 99.29, 82.64, 48.62, 44.82]

In [22]:
a = [82.59, 87.29, 85.55, 99.37, 29.53, 22.14]

In [16]:
a = [22.14, 29.53, 85.55, 82.59, 87.29, 99.37]

In [27]:
a = [65.05, 52.21, 62.30, 93.53, 88.83, 87.59, 99.42]

In [10]:
a = [0,0,1.14, 85.92, 87.22, 90.25, 93.13]

In [15]:
a = [60.30, 52.44, 26.63, 93.69 ,88.44, 85.42, 99.46]

In [10]:
np.mean(a), np.std(a)

(75.05285714285716, 22.64143465563316)

In [11]:
statistics.harmonic_mean(a)

66.42890631735331

In [34]:
data = 'pubmed'

In [35]:
adj = pickle.load(open(data+'_adj.pkl', 'rb'))
feat = pickle.load(open(data+'_feat.pkl', 'rb'))

In [46]:
adj = nx.from_scipy_sparse_matrix(adj)

In [47]:
adj.number_of_nodes()

4039

In [48]:
adj.number_of_edges()

88234

In [49]:
np.mean(np.array(adj.degree())[:,1])

43.69101262688784

In [50]:
nx.density(adj)

0.010819963503439287

In [53]:
preds = nx.jaccard_coefficient(adj, ([3,5], [8,7]))

In [54]:
list(preds)

[(3, 5, 0.0), (8, 7, 0.0)]

In [55]:
k = []

In [56]:
for v,u,p in list(preds):
    k.append(p)

In [57]:
np.array(k)

array([], dtype=float64)

In [58]:
adj.shape[0]

AttributeError: 'Graph' object has no attribute 'shape'

In [41]:
filename = f'facebook.txt'
g = nx.read_edgelist(filename,create_using=nx.Graph(), nodetype = int,  data=(("weight", float),))
adj_label = nx.adjacency_matrix(g, nodelist = sorted(g.nodes()))
adj = (adj_label > 0).astype('int') # to binary

In [8]:
adj.shape

(4039, 4039)

In [45]:
net = nx.from_scipy_sparse_matrix(adj)

In [145]:
len(net.nodes())

4039

In [126]:
torch.tensor(feat.toarray())

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [54]:
test_val = pickle.load(open(data+'_tvtEdges_val0.1test0.2.pkl', 'rb'))

In [95]:
a, b = adj.tocoo().row, adj.tocoo().col

In [98]:
torch.tensor(a)

tensor([    0,     0,     0,  ..., 19715, 19716, 19716], dtype=torch.int32)

In [97]:
b

array([    0,  1378,  1544, ..., 19715, 16030, 19716], dtype=int32)

In [73]:
len(test_val)

6

In [109]:
test_val[0].tocoo().data

array([1., 1., 1., ..., 1., 1., 1.])

In [117]:
torch.tensor(test_val[2]).size()

torch.Size([455, 2])

In [107]:
torch.sparse_csr_tensor(test_val[0])

TypeError: sparse_csr_tensor() received an invalid combination of arguments - got (csr_matrix), but expected one of:
 * (object crow_indices, object col_indices, object values, tuple of ints size, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (object crow_indices, object col_indices, object values, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [64]:
test_val[1].shape

(5530071, 2)

In [75]:
test_val[2].shape

(455, 2)

In [76]:
test_val[3].shape

(455, 2)

In [81]:
test_val[4].shape

(910, 2)

In [82]:
test_val[5].shape

(910, 2)

In [36]:
nx.from_scipy_sparse_matrix(adj)

In [37]:
feat.toarray().shape

(19717, 500)

In [38]:
np.log(feat.toarray().shape[0])

9.889236486766269

In [39]:
g = nx.read_edgelist('facebook.txt',create_using=nx.Graph(), nodetype = int,  data=(("weight", float),))
adj_label = nx.adjacency_matrix(g, nodelist = sorted(g.nodes()))
adj_label = (adj_label > 0).astype('int') # to binary

In [44]:
np.log(g.number_of_nodes())

8.303752415563412

In [46]:
adj_label.toarray()

array([[0, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
d_names = ['ogbl-ppa', 'ogbl-collab', 'ogbl-ddi', 'ogbl-citation2']
d_name = d_names[2]
torch.manual_seed(777)
device = 'cpu'

dataset = PygLinkPropPredDataset(name=d_name,
                                 transform=T.ToSparseTensor())
data = dataset[0]
adj_t = data.adj_t.to(device)

data = data.to(device)

adj = adj_t.to_scipy()
net = nx.from_scipy_sparse_matrix(adj)

/opt/conda/lib/python3.7/site-packages/torch_sparse/storage.py:14: UserWarning: `layout` argument unset, using default layout "coo". This may lead to unexpected behaviour.
  warnings.warn('`layout` argument unset, using default layout '


In [46]:
com = torch.load('/data/private/graph/com_det/ddi_com_async_fluid.pt')

In [ ]:
for c in com.communities:
    subnet = nx.subgraph(net, c)
    anchor_node1 = sorted(subnet.degree(), key=lambda x : x[1], reverse=True)[0][0]
    anchor_node2 = sorted(nx.closeness_centrality(subnet).items(), key=lambda x : x[1], reverse=True)[0][0]
    anchor_node3 = sorted(nx.betweenness_centrality(subnet).items(), key=lambda x : x[1], reverse=True)[0][0]
    print (anchor_node1, anchor_node2, anchor_node3)

352 352 326


In [ ]:
com = torch.load('/data/private/graph_2/ddi_com_async_fluid.pt')

In [ ]:
for c in com.communities:
    subnet = nx.subgraph(net, c)
    anchor_node1 = sorted(subnet.degree(), key=lambda x : x[1], reverse=True)[0][0]
    anchor_node2 = sorted(nx.closeness_centrality(subnet).items(), key=lambda x : x[1], reverse=True)[0][0]
    anchor_node3 = sorted(nx.betweenness_centrality(subnet).items(), key=lambda x : x[1], reverse=True)[0][0]
    print (anchor_node1, anchor_node2, anchor_node3)


In [57]:
pe_low = torch.load('/data/private/graph_2/ddi_pe_async_fluid_low.pt')

In [30]:
pe_low.shape

(4267, 8)

In [31]:
pe = torch.load('/data/private/graph_2/ddi_pe_async_fluid_high.pt')

In [32]:
pe = torch.load('/data/private/graph_2/com_det/ddi_pe_async_fluid.pt')

In [33]:
cnt = 0
for i in range(pe.shape[0]):
    for j in range(i+1, pe.shape[0]):
        if np.array_equal(pe[i], pe[j]):
            cnt += 1

In [34]:
cnt

430699

In [35]:
cnt/9101511

0.047321702956794755

In [62]:
cnt = 0
for i in range(pe_low.shape[0]):
    for j in range(i+1, pe_low.shape[0]):
        if np.array_equal(pe[i], pe[j]):
            cnt += 1

In [63]:
cnt

378259

In [64]:
cnt/9101511

0.041560022286409364

In [52]:
pe_low

NameError: name 'pe_low' is not defined

In [ ]:
cnt = 0
for i in range(pe.shape[0]):
    for j in range(i+1, pe.shape[0]):
        if np.array_equal(pe[i], pe[j]):
            cnt += 1

In [27]:
cnt

163993

In [33]:
cnt = 0
for i in range(pe.shape[0]):
    for j in range(i+1, pe_rand.shape[0]):
        if np.array_equal(pe_rand[i], pe_rand[j]):
            cnt += 1

In [34]:
cnt

505970

In [39]:
cnts = []
for k in range(6):
    pe_rand = torch.load('/data/private/graph_2/ddi_pe_async_fluid_rand'+str(k)+'.pt')
    cnt = 0
    for i in range(pe.shape[0]):
        for j in range(i+1, pe_rand.shape[0]):
            if np.array_equal(pe_rand[i], pe_rand[j]):
                cnt += 1
    cnts.append(cnt)

In [40]:
np.mean(cnts), np.std(cnts)

(362889.0, 109243.00941631613)

In [43]:
(4267*4266)/2

9101511.0

In [47]:
109243/9101511

0.012002732293571914